language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-hipchat.gemspec
- gem install sensu-plugins-hipchat-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: JUp7DPNRdDNWDxUjAUpEkQLJbWVE+WFtMRvB/HcoMYP8EGVXycZpU8i9aYo7n44/P0SPdo06VVuFUB3cOL67vzji4vvcUbkpdI932RRkBlvY8aSIgOYrhosXHi91o3lj+drh7Q+PsyLSec0pctr8YcxllTdRRvHYCbLRbx9RX3U=
  gem: sensu-plugins-hipchat
  on:
    tags: true
    all_branches: true
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-hipchat
